#!/bin/bash
cd ~/.ccr_black_diamond/
conky -c ~/.ccr_black_diamond/.conkycpu &
conky -c ~/.ccr_black_diamond/.conkynet &
conky -c ~/.ccr_black_diamond/.conkytime &
conky -c ~/.ccr_black_diamond/.conkyx

